routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('libros', 'LibrosController');
Route::resource('autores','AutoresController');
Route::resource('editoriales', 'EditorialesController');

Route::resource('temas','TemasController');

app/Autores.php
<?php

namespace MiLibreria;

use Illuminate\Database\Eloquent\Model;

class Autores extends Model
{
    //
    protected $guarded = [];
}

app/Http/Controllers/AutoresController.php
<?php

namespace MiLibreria\Http\Controllers;

use MiLibreria\Autores;
use Illuminate\Http\Request;

class AutoresController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $autores = Autores::orderBy('id', 'DESC')->paginate();
        return view('autores.index', compact('autores'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \MiLibreria\Autores  $autores
     * @return \Illuminate\Http\Response
     */
    public function show(Autores $autores)
    {
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \MiLibreria\Autores  $autores
     * @return \Illuminate\Http\Response
     */
    public function edit(Autores $autores)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \MiLibreria\Autores  $autores
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Autores $autores)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \MiLibreria\Autores  $autores
     * @return \Illuminate\Http\Response
     */
    public function destroy(Autores $autores)
    {
        //
    }
}

resources/views/autores/index.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
	<div class="row">
		<h2>Listado de Autores:
		<a href="{{ route('libros.create') }}" class="btn btn-primary btn-lg pull-right"><i class="fa fa-users" aria-hidden="true"> Nuevo</i></a>
		</h2>
		<table class="table table-hover table-striped">
			<thead>
				<tr>
					<th width="20px">ID</th>
					<th>Nombres</th>
					<th>Apellido Paterno</th>
					<th>Apellido Materno</th>
					<th>Pais</th>
					<th colspan="3">Acciones</th>
				</tr>
			</thead>
			<tbody>
				@foreach($autores as $autor)
				<tr>
					<td>{{ $autor->id }}</td>
					<td>{{ $autor->nombres }}</td>
					<td>{{$autor->apellidoPrimero}}</td>
					<td>{{$autor->apellidoSegundo}}</td>
					<td>{{$autor->pais}}</td>
					<td>ver</td>
					<td>editar</td>
					<td>borrar</td>
				</tr>
				@endforeach
			</tbody>
		</table>
		{!!$autores->render() !!}
        
    </div>
</div>

@endsection